version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:3000"   # Expose port 3000 from the container to port 8080 on the host
    environment:
      - NODE_ENV=production
      - TMDB_API_KEY=3c5af44d51ce89d48dd3dff3894d14d3   # Replace with your TMDB API key
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
